export const httpMethods: string[] = [
    "CONNECT",
    "DELETE",
    "GET",
    "HEAD",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    "TRACE",
];

export const httpStatusCodes: Map<number, string> = new Map<number, string>([
    // 1xx: Informational
    [100, "Continue - server received headers, proceed with body"],
    [101, "Switching Protocols - protocol change accepted"],
    [102, "Processing (WebDAV) - request is still being handled"],
    [103, "Early Hints - headers sent before final response"],

    // 2xx: Success
    [200, "OK - request succeeded"],
    [201, "Created - resource successfully created"],
    [202, "Accepted - request accepted but not completed"],
    [203, "Non-Authoritative Information - modified proxy response"],
    [204, "No Content - successful, no response body"],
    [205, "Reset Content - reset document view"],
    [206, "Partial Content - delivery of partial resource"],
    [207, "Multi-Status (WebDAV) - multiple status values"],
    [208, "Already Reported (WebDAV) - previously listed"],
    [226, "IM Used - delta encoding applied to resource"],

    // 3xx: Redirection
    [300, "Multiple Choices - multiple representations available"],
    [301, "Moved Permanently - permanent redirect to new URL"],
    [302, "Found (temporary) - use GET at new Location"],
    [303, "See Other - redirect using GET"],
    [304, "Not Modified - cache still valid"],
    [305, "Use Proxy - deprecated"],
    [306, "Switch Proxy - no longer used"],
    [307, "Temporary Redirect - preserve HTTP method"],
    [308, "Permanent Redirect - preserve method on redirect"],

    // 4xx: Client errors
    [400, "Bad Request - malformed request syntax"],
    [401, "Unauthorized - authentication required"],
    [402, "Payment Required - reserved for future use"],
    [403, "Forbidden - authenticated but access denied"],
    [404, "Not Found - resource not found"],
    [405, "Method Not Allowed - method not supported"],
    [406, "Not Acceptable - cannot satisfy Accept headers"],
    [407, "Proxy Authentication Required - proxy login needed"],
    [408, "Request Timeout - client took too long"],
    [409, "Conflict - request conflicts with current state"],
    [410, "Gone - resource permanently removed"],
    [411, "Length Required - Content-Length header missing"],
    [412, "Precondition Failed - conditional headers not met"],
    [413, "Payload Too Large - entity too large"],
    [414, "URI Too Long - request URI too long"],
    [415, "Unsupported Media Type - format not supported"],
    [416, "Range Not Satisfiable - invalid range request"],
    [417, "Expectation Failed - Expect header unmet"],
    [421, "Misdirected Request - wrong server handling"],
    [422, "Unprocessable Entity - semantic errors (WebDAV)"],
    [423, "Locked - resource is locked"],
    [424, "Failed Dependency - dependent request failed"],
    [425, "Too Early - request replay risk"],
    [426, "Upgrade Required - must switch protocols, e.g. HTTPS"],
    [428, "Precondition Required - safe update conditions required"],
    [429, "Too Many Requests - rate limiting"],

    // 5xx: Server errors
    [500, "Internal Server Error - generic server failure"],
    [501, "Not Implemented - server lacks support"],
    [502, "Bad Gateway - invalid upstream response"],
    [503, "Service Unavailable - overloaded or down"],
    [504, "Gateway Timeout - upstream server timed out"],
    [505, "HTTP Version Not Supported - protocol version not supported"],
    [506, "Variant Also Negotiates - misconfigured content negotiation"],
    [507, "Insufficient Storage - cannot store representation"],
    [508, "Loop Detected (WebDAV) - infinite processing loop"],
    [510, "Not Extended - missing required extensions"],
    [511, "Network Authentication Required - login to gain network access"],
]);
